name: week_four
description: "A new Flutter project."
publish_to: 'none'  # Keeps the package private, remove to publish

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.6
  encrypt: ^5.0.1
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/idea.png
    - images/questionmark.png
    - images/stop.png
